### ISSUE TITLE
APPRISE_HOST does not work with container host name

### ISSUE THREAD

**Issue by ChrWieg** [FoxxMD/komodo-utilities#2]
I am running the komodo-apprise-alerter:latest via docker compose in the a stack together with caronc/apprise:latest. It works very well when I use the ip address of the apprise service as APPRISE_HOST (APPRISE_HOST=172.30.0.37:8000). Since the ip address is dynamicly assigned by docker using the ip address is not save.
Unfortunately it does not work with the containers host name wich is just "apprise" (APPRISE_HOST=apprise:8000). With this configuration I get the error:

**apprisealerter  | Caused by TypeError: Url scheme 'apprise' not supported**

Log of the container:

apprise         | Apprise API Super User Startup
apprisealerter  | Apprise Host Config URL: 'apprise:8000' => Normalized: 'apprise:8000'
apprisealerter  | Using Apprise @ apprise:8000
apprisealerter  | Pushing to stateless URLs 'http://apprise:8000/notify/apprise'
apprisealerter  | Error: Unable to detect if server is reachable
apprisealerter  |     at parseAppriseOptions (file:///app/notifiers/apprise/program.ts:51:23)
apprisealerter  |     at Object.runMicrotasks (ext:core/01_core.js:672:26)
apprisealerter  |     at processTicksAndRejections (ext:deno_node/_next_tick.ts:59:10)
apprisealerter  |     at runNextTicks (ext:deno_node/_next_tick.ts:76:3)
apprisealerter  |     at eventLoopTick (ext:core/01_core.js:182:21)
apprisealerter  |     at async program (file:///app/notifiers/apprise/program.ts:117:26)
apprisealerter  |     at async file:///app/notifiers/apprise/main.ts:3:1
apprisealerter  | Caused by Error: connect ECONNREFUSED 127.0.0.1:80 - Local (undefined:undefined)
apprisealerter  |     at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
apprisealerter  |     at __node_internal_exceptionWithHostPort (ext:deno_node/internal/errors.ts:217:10)
apprisealerter  |     at TCPConnectWrap._afterConnect [as oncomplete] (node:net:171:16)
apprisealerter  |     at TCP.afterConnect (ext:deno_node/internal_binding/connection_wrap.ts:43:11)
apprisealerter  |     at ext:deno_node/internal_binding/tcp_wrap.ts:306:14
apprisealerter  |     at eventLoopTick (ext:core/01_core.js:175:7)
apprisealerter  | Listening on http://0.0.0.0:7000/
apprise         | 2025-04-27 10:22:58,224 INFO Set uid to user 1000 succeeded
apprise         | 2025-04-27 10:22:58,231 INFO supervisord started with pid 38
apprise         | 2025-04-27 10:22:59,237 INFO spawned: 'gunicorn' with pid 39
apprise         | 2025-04-27 10:22:59,242 INFO spawned: 'nginx' with pid 40
apprise         | 2025-04-27 10:23:00,245 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
apprise         | 2025-04-27 10:23:00,245 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
apprise         | [2025-04-27 10:23:00 +0000] [39] [INFO] Starting gunicorn 23.0.0
apprise         | [2025-04-27 10:23:00 +0000] [39] [INFO] Listening at: http://0.0.0.0:8080 (39)
apprise         | [2025-04-27 10:23:00 +0000] [39] [INFO] Using worker: gevent
apprise         | [2025-04-27 10:23:00 +0000] [47] [INFO] Booting worker with pid: 47
apprisealerter  | Recieved data from apprisealerter:7000...
apprisealerter  | == Alert Summary ==
apprisealerter  | Title    : [OK] Test
apprisealerter  | Subtitle : for apprise
apprisealerter  | Message  : ✅
apprisealerter  | Resolved : True
apprisealerter  | Pushing Alert undefined for <removedsecretid>-Test
apprisealerter  | Error: Failed to send notification using URLs
apprisealerter  |     at pushAlert (file:///app/notifiers/apprise/program.ts:202:31)
apprisealerter  |     at eventLoopTick (ext:core/01_core.js:175:7)
apprisealerter  |     at async doAlert (file:///app/notifiers/apprise/program.ts:209:13)
apprisealerter  |     at async file:///app/notifiers/common/notifierUtils.ts:27:20
apprisealerter  |     at async file:///app/notifiers/apprise/program.ts:234:9
apprisealerter  |     at async ext:deno_http/00_serve.ts:369:18
**apprisealerter  | Caused by TypeError: Url scheme 'apprise' not supported**
apprisealerter  |     at mainFetch (ext:deno_fetch/26_fetch.js:152:43)
apprisealerter  |     at ext:deno_fetch/26_fetch.js:353:9
apprisealerter  |     at new Promise (<anonymous>)
apprisealerter  |     at fetch (ext:deno_fetch/26_fetch.js:316:18)
apprisealerter  |     at callApi (file:///app/notifiers/apprise/program.ts:80:28)
apprisealerter  |     at pushAlert (file:///app/notifiers/apprise/program.ts:195:36)
apprisealerter  |     at doAlert (file:///app/notifiers/apprise/program.ts:209:19)
apprisealerter  |     at file:///app/notifiers/apprise/program.ts:234:41
apprisealerter  |     at file:///app/notifiers/common/notifierUtils.ts:27:26
apprisealerter  |     at file:///app/notifiers/apprise/program.ts:234:15

**Comment by FoxxMD** [comment]
Likely your `komodo-apprise-alerter` service is not running in the same stack as the `caronc/apprise` service. Docker containers can only use container names with hostname resolution if they are in the same [user-defined network](https://blog.foxxmd.dev/posts/migrating-to-traefik/#user-defined-vs-default-bridge-networking).

To use a user-defined network for these two service either:

* both services must be in the same stack (easiest)
* you must create an external, attachable bridge network and both stacks must use it under [`networks`](https://docs.docker.com/compose/how-tos/networking/#use-a-pre-existing-network)
  * if stacks are on different machines the external network be must an [`overlay`](https://blog.foxxmd.dev/posts/migrating-to-traefik/#swarm-and-overlay)

**Comment by ChrWieg** [comment]
Thank you very much for your reply. Actually both services are in the same stack. Here is my compose.yaml:
```yaml
services:
  apprise:
    image: caronc/apprise:latest
    container_name: apprise
    restart: unless-stopped
    hostname: apprise
    environment:
      - APPRISE_STATEFUL_MODE=simple
      - APPRISE_WORKER_COUNT=1  
      - COMPOSE_BAKE=true     
    # ports:
    #   - 8000:8000
    volumes:
      - apprise:/opt/apprise/webapp
      - config:/config
      - attach:/attach
      - plugin:/plugin
    labels:
      - traefik.http.routers.apprise.rule=Host('apprise.[sensitive information removed].de')
      - traefik.http.routers.apprise.tls=true
      - traefik.http.services.apprise.loadbalancer.server.port=8000
      - traefik.http.middlewares.apprise.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.apprise.ipwhitelist.sourcerange=[sensitive information removed] #
      - traefik.http.routers.apprise.middlewares=admin-whitelist@docker
    networks:
      default:

  komodo-apprise-alerter:
    container_name: apprisealerter
    image: foxxmd/komodo-apprise-alerter:latest
    restart: unless-stopped
    depends_on:
      - apprise
    environment:
      - APPRISE_HOST=172.30.0.37:8000 #here I would like to set the container name 'apprise' instead of the ip address
      - MARKDOWN=true
      - APPRISE_STATELESS_URLS=http://apprise:8000/notify/apprise
    # env_file:
    #   - ./.env
    # ports:
    #   - "7000:7000"
    networks:
      default:

volumes:
    apprise: 
    config:
    attach:
    plugin:

networks:
  default:
      external: true
      name: gateway
```

**Comment by FoxxMD** [comment]
Your stack looks okay to me...Is there a reason your default network is external? Could you try creating another, non-external network for use with the two containers? IE

```yaml
services:
  apprise:
    networks:
      - default
      - appriseInternal
    # ...

  komodo-apprise-alerter:
    networks:
      - default
      - appriseInternal
    # ...
# ...

networks:
  default:
      external: true
      name: gateway
  appriseInternal:
```
